name: trajectory_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.70.2 # https://pub.dev/packages/fl_chart/install
  flutter_svg: ^2.0.17 # https://pub.dev/packages/flutter_svg/install
  cupertino_icons: ^1.0.8 
  syncfusion_flutter_sliders: ^28.2.11 # https://pub.dev/packages/syncfusion_flutter_sliders/install
  flutter_icon_shadow: ^2.0.7 # https://pub.dev/packages/flutter_icon_shadow/install


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
